# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aila's CS 373 Blog
email: ailaenos@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm only doing the extra credit. Here, I'll give my thoughts on each week of class.
baseurl: "/SWEblog" # the subpath of your site, e.g. /blog
url: "http://ailae.github.io" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  ailae

# Build settings
markdown: kramdown
